name: Create Add-On Releases

on:
  push:
    tags:
      - 'v*.*.*'

env:
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Build and Release Add-Ons
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -e
        for addon in WoWAR WoWPL WoWTR; do
          echo "Building $addon..."
          mkdir -p builds/$addon
          if [ -d "$addon" ]; then
            cp -r $addon/* builds/$addon/
          else
            echo "Warning: $addon directory not found, skipping..."
            continue
          fi
          
          if [ -d "common" ]; then
            cp -r common/* builds/$addon/
          else
            echo "Warning: common directory not found, skipping..."
          fi
          
          (cd builds/$addon && zip -r ../$addon.zip .)
          
          echo "Creating release for $addon..."
          release_response=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{
              "tag_name": "${{ github.ref_name }}",
              "name": "'$addon'_release_${{ github.ref_name }}",
              "body": "Release notes for '$addon' ${{ github.ref_name }}",
              "draft": false,
              "prerelease": false
            }')
          
          echo "Release creation response: $release_response"
          
          release_url=$(echo "$release_response" | jq -r .upload_url | sed 's/{?name,label}//g')
          
          if [ -z "$release_url" ] || [ "$release_url" == "null" ]; then
            echo "Error: Failed to create release. API response: $release_response"
            exit 1
          fi
          
          echo "Uploading $addon.zip to release..."
          upload_response=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/zip" \
            -H "Accept: application/vnd.github.v3+json" \
            --data-binary @builds/$addon.zip \
            "${release_url}?name=$addon.zip")
          
          echo "Upload response: $upload_response"
          
          if ! echo "$upload_response" | jq -e .id > /dev/null; then
            echo "Error: Failed to upload asset. API response: $upload_response"
            exit 1
          fi
          
          echo "Successfully released and uploaded $addon"
        done
