name: Create Add-On Releases

on:
  push:
    tags:
      - 'v*.*.*'

env:
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Build and Release Add-Ons
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        for addon in WoWAr WoWPL WoWTR; do
          echo "Building $addon..."
          mkdir -p builds/$addon
          cp -r $addon/* builds/$addon/
          cp -r common/* builds/$addon/
          (cd builds/$addon && zip -r ../$addon.zip .)
          
          echo "Creating release for $addon..."
          release_url=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{
              "tag_name": "${{ github.ref_name }}",
              "name": "'$addon'_release_${{ github.ref_name }}",
              "body": "Release notes for '$addon' ${{ github.ref_name }}",
              "draft": false,
              "prerelease": false
            }' | jq -r .upload_url | sed 's/{?name,label}//g')
          
          echo "Uploading $addon.zip to release..."
          curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/zip" \
            -H "Accept: application/vnd.github.v3+json" \
            --data-binary @builds/$addon.zip \
            "${release_url}?name=$addon.zip"
        done
